name: Update internships README

on:
  schedule:
    - cron: "15 13 * * *"   # 9:15 AM ET daily
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data folder
        run: mkdir -p data

      - name: Scrape postings
        run: python scripts/scraper.py --filters filters.yaml --input data/postings.json --output data/postings.json

      - name: Normalize postings
        run: python scripts/normalize.py

      - name: Show first 5 rows
        run: |
          python - << 'PY'
          import json
          with open('data/postings.json', 'r', encoding='utf-8') as f:
              arr = json.load(f)
          print("rows:", len(arr))
          print(json.dumps(arr[:5], indent=2, ensure_ascii=False))
          PY

      - name: Render README
        run: python scripts/render_readme.py

      - name: Commit README directly to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update internships README"
          file_pattern: |
            README.md
            data/postings.json
          branch: main
