name: Update internships README

on:
  schedule:
    - cron: "15 13 * * *"   # 9:15 AM ET daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data folder
        run: mkdir -p data

      - name: Scrape postings
        run: |
          python scripts/scraper.py \
            --filters filters.yaml \
            --output data/postings.json \
            --seed jobs.json

      - name: Render README
        run: python scripts/render_readme.py

      - name: Commit README directly to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update internships README"
          file_pattern: |
            README.md
            data/postings.json
          branch: main
