name: Auto Update
on:
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * *"  # daily at 07:17 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater
        run: |
          python update.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: automated update"
          title: "Automated update"
          body: "This PR was created automatically by the daily updater."
          branch: chore/auto-update
          delete-branch: true
