name: Update internships README

on:
  schedule:
    - cron: "15 13 * * *"   # 9:15 AM ET daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Replace this with your actual scraper command
      - name: Scrape postings (temporary placeholder)
        run: |
          echo "[]" > data/postings.json

      - name: Render README
        run: |
          python scripts/render_readme.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: auto-update internships README"
          title: "Automated update"
          body: "This PR was created automatically by the daily updater."
          branch: chore/auto-update
          delete-branch: true
