name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * *"  # daily at 07:17 UTC

permissions:
  contents: write  # required to push to the repo

concurrency:
  group: auto-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # needed for clean commits

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater
        run: |
          python update.py

      # ⬇️ Direct commit to main if README/jobs.json changed
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 auto: update README and jobs registry"
          branch: main
          file_pattern: README.md jobs.json
